repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2  # Use the latest version
    hooks:
      - id: ruff
      - id: ruff-format

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2  # Use the latest version
  #   hooks:
  #     - id: mypy