
name: Coverage Analysis

on:
  pull_request:
    branches: [ "*" ]
permissions:
  pull-requests: write
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install --with dev
    - name: Test
      run: poetry run pytest --cov=photo_id --cov-report xml:coverage.xml
    - name: Get Cover
      uses: orgoro/coverage@v3.1
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: .1
          thresholdNew: .9
          thresholdModified: 0
